# Generated by Django 4.1.7 on 2023-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagem_alter_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
