# Generated by Django 4.1.7 on 2023-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
