# Generated by Django 4.1.7 on 2023-03-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='descricao',
        ),
    ]
