# Generated by Django 4.1.7 on 2023-03-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='descricao',
        ),
    ]
