# Generated by Django 4.1.7 on 2023-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_descricao_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
